theme = "awesome-identity"
baseURL = "https://example.com"
title = "Awesome Identity for Hugo"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Mohamed"
  lastname = "Muzamil"
  title = "Data Scientist"
  bio = """I am a recent graduate from Dalhousie University with a Master in Computer science. My research interests lie in leveraging Visualization to explore insights from data and use this knowledge to build intelligent systems to help make an informed decision."""

## Footer Configurations
[params.footer]
  copyright = "© 2019-2020 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = false
